# Generated by Django 3.1.4 on 2020-12-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('director', models.TextField()),
                ('guionistas', models.TextField()),
                ('estreno', models.IntegerField()),
                ('protagonistas', models.TextField()),
                ('duracion', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=1)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
