# Generated by Django 3.1.4 on 2020-12-20 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDick', '0002_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='lista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MovieDick.lista'),
            preserve_default=False,
        ),
    ]
